### ISSUE TITLE
OPX NAS: continuous syslog entries

### ISSUE THREAD

**Issue by vnam1** [open-switch/opx-nas-common#22]
On OPX 2.3.0, seeing these logs continuously in normal operation. Does it indicate any issue?

May 31 04:08:16 leaf-1 opx_nas_daemon[549]: [INTERFACE:NAS-COM-INT-GET], Get request handler not present
May 31 04:08:16 leaf-1 opx_nas_daemon[549]: [INTERFACE:NAS-COM-INT-GET], Get request handler not present
May 31 04:08:21 leaf-1 opx_nas_daemon[549]: [INTERFACE:NAS-COM-INT-GET], Get request handler not present
May 31 04:08:21 leaf-1 opx_nas_daemon[549]: [INTERFACE:NAS-COM-INT-GET], Get request handler not present
May 31 04:08:21 leaf-1 opx_nas_daemon[549]: [INTERFACE:NAS-COM-INT-GET], Get request handler not present
May 31 04:08:21 leaf-1 opx_nas_daemon[549]: [INTERFACE:NAS-COM-INT-GET], Get request handler not present
May 31 04:08:23 leaf-1 opx_nas_daemon[549]: [INTERFACE:INTF-C], Failed to get if_info
May 31 04:08:23 leaf-1 opx_nas_daemon[549]: [INTERFACE:NAS-COM-INT-GET], Get request handler not present
May 31 04:08:23 leaf-1 opx_nas_daemon[549]: [INTERFACE:INTF-C], Failed to get if_info
May 31 04:08:23 leaf-1 opx_nas_daemon[549]: [INTERFACE:NAS-COM-INT-GET], Get request handler not present
May 31 04:08:24 leaf-1 opx_nas_daemon[549]: [INTERFACE:INTF-C], Failed to get if_info
May 31 04:08:24 leaf-1 opx_nas_daemon[549]: [INTERFACE:NAS-COM-INT-GET], Get request handler not present

**Comment by jeffyin-dell** [comment]
Sorry I missed this until now. 

@nchervela have you seen this in your testing?
@vnam1 have you seen this in OPX 2.3.1?

**Comment by nchervela** [comment]
@jeff-yin no, I haven't seen this in my testing.

**Comment by vnam1** [comment]
I don't see this with 2.3.1. can be closed. Thanks

**Comment by jeffyin-dell** [comment]
Thanks all!
