### ISSUE TITLE
opx-switch-shell L3 route get fails wih the ipv4 prefix len is out of range

### ISSUE THREAD

**Issue by disaster123** [open-switch/opx-nas-common#30]
I can't get L3 route get to work. It always fails with prefix len is out of range.

```
root@OPX:~# opx-switch-shell "L3 route get ip=89.0.0.1 mask=24"
  Code 0x213A088 (fail):
Text        : SOC_SAND_PP_IPV4_SUBNET_PREF_OUT_OF_RANGE_ERR
the ipv4 prefix len is out of range 
ipv4 prefix length range 0-32.
Procedure id: 0x109D (Mod: SOC_SAND module, Proc: SOC_SAND_PP_IPV4_SUBNET_VERIFY)
0:arad_pp_frwrd_ipv4_vrf_route_get_verify: soc_sand function returned error
0:arad_pp_frwrd_ipv4_vrf_route_get_verify: Function returned an error (var_a=0, var_b=0)
0:soc_ppd_frwrd_ipv4_vrf_route_get: soc_sand function returned error
0:soc_ppd_frwrd_ipv4_vrf_route_get: Function returned an error (var_a=0, var_b=0)
<nounit>:handle_sand_result: SOC_SAND Error Code 0x0 (fail):
Text : SOC_SAND_PP_IPV4_SUBNET_PREF_OUT_OF_RANGE_ERR
the ipv4 prefix len is out of range 
ipv4 prefix length range 0-32.
Procedure id: 0x19474 (Mod: ARAD PP module, Proc: Unknown_procedure)
0:_bcm_ppd_frwrd_ipv4_vrf_route_get: Internal error
0:_bcm_ppd_frwrd_ipv4_vrf_uc_route_get: get vrf route failed
Route get returned: Internal error
SAI.0> 

```

**Comment by jeffyin-dell** [comment]
@Tejaswi-Goel -- assigned this one to you, thanks

**Comment by atanu-mandal** [comment]
Hi @disaster123 , this is vendor npu shell command and any related issue may not be supported in this forum. BTW you may want to try with passing vrf=1 and the mask in different format. e.g.                          
                                                                                                                                           `l3 route get ip=1.1.1.1 mask=255.255.255.0 vrf=1`                                                                                                                                                                                                                                                         

> 
Route get returned: Ok
fec_id: 4096
Accessed: NO

Hope that helps. Thanks.

**Comment by atanu-mandal** [comment]
Given the response is provided I am closing the issue, please reopen if required.

**Comment by disaster123** [comment]
Sorry! Thanks!
